build
  publish = "public"
  command = "npm run build"
  
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES = "true"

# Configuración para Gatsby
[[plugins]]
  package = "@netlify/plugin-gatsby"

# Redirects para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"], Country = ["US"]}

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Configuración para archivos estáticos
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    # netlify.toml
[build]
  publish = "gatsby-main/public"
  command = "cd gatsby-main && npm run build"

[[redirects]]
  from = "/app/*"
  to = "/.netlify/functions/advanced-features/:splat"
  status = 200

[functions]
  directory = "advanced-features/.next"
