# This is a basic workflow to help you get started with Actions

name: CI/CD Sitio Web -IPS Figuras SST Cucuta SAS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
# Archivo: .github/workflows/process-3d.yml
name: Process 3D Models

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  process-3d:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📋 Checkout repository
      uses: actions/checkout@v3
      
    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: 📦 Install GLTF Tools
      run: |
        npm install -g gltf-pipeline
        # Draco compression ya está incluido en gltf-pipeline
        # NO necesitamos: sudo apt-get install -y draco-tools
        
    - name: 🗂️ Create output directory
      run: mkdir -p processed-models
      
    - name: 🔄 Process 3D models
      run: |
        # Procesar archivos GLTF/GLB con compresión Draco
        for file in models/*.{gltf,glb}; do
          if [ -f "$file" ]; then
            filename=$(basename "$file")
            echo "Processing: $filename"
            gltf-pipeline -i "$file" -o "processed-models/$filename" --draco.compressionLevel 7
          fi
        done
        
    - name: 📤 Upload processed models
      uses: actions/upload-artifact@v3
      with:
        name: processed-3d-models
        path: processed-models/